spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb_dev
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

payu:
  account:
    id: 512321
  merchant:
    id: 508029
  api:
    login: pRRXKOl8ikMmt9u
    key: 4Vj8eK4rloUd272L48hsrarnUA
    url: https://sandbox.api.payulatam.com
  transaction:
    test: true
    language: "es"
    command: "SUBMIT_TRANSACTION"
    type: "AUTHORIZATION_AND_CAPTURE"
    paymentCountry: "CO"
